server:
  port: 8081

spring:
  application:
    name: StudyPost
  profiles:
    active: secret # secret 프로필 활성화

#  decorator:
#    datasource:
#      p6spy:
#        enable-logging: true
#        # 쿼리 포맷팅을 위한 커스텀 설정 (Multiline 등)
#        logging: slf4j
#        multiline: true

  datasource:
    url: jdbc:mysql://localhost:3306/20260107
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: false
        highlight_sql: true


  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# P6SPY 로깅 확인용(유지보수 더 좋게 하기 위해 로그를 보기 쉽게 보여줌)
  logging:
    level:
      org.hibernate.SQL: off
      org.hibernate.orm.jdbc.bind: off
      p6spy: info

  # AWS 설정 (최신 방식) - 민감 정보는 application-secret.yaml로 이동
  cloud:
    aws:
      region:
        static: ap-northeast-2
      stack:
        auto: false
